## Hellow World

In [2]:
print("Hello World")

Hello World


In [3]:
import numpy as np

In [27]:
array1 = np.genfromtxt("./data/lab1.csv", dtype='float', delimiter=',')
array1

array([[ 4.28517983e+00, -3.06161700e-15, -1.57079633e+01],
       [ 4.16158172e+00, -1.56016723e+00, -1.53906307e+01],
       [ 3.59973217e+00, -2.96453965e+00, -1.50732981e+01],
       [ 1.99456845e+00, -4.07287976e+00, -1.47559655e+01],
       [ 1.37444086e+00, -4.77451121e+00, -1.44386329e+01],
       [ 3.95480550e-01, -4.99937064e+00, -1.41213003e+01],
       [ 1.36597596e+00, -4.72500409e+00, -1.38039677e+01],
       [ 8.58003619e-01, -3.97880920e+00, -1.34866351e+01],
       [ 3.20752121e+00, -2.83529932e+00, -1.31693025e+01],
       [ 3.78656065e+00, -1.40866278e+00, -1.28519699e+01],
       [ 3.15400343e+00,  1.58639667e-01, -1.25346374e+01],
       [ 3.55363895e+00,  1.71010072e+00, -1.22173048e+01],
       [ 2.21616208e+00,  3.09079493e+00, -1.18999722e+01],
       [ 6.35491623e-01,  4.16284927e+00, -1.15826396e+01],
       [ 3.25210817e+00,  4.81921079e+00, -1.12653070e+01],
       [ 7.06689492e-02,  4.99433670e+00, -1.09479744e+01],
       [ 4.10609592e+00,  4.67073930e+00

In [28]:
array1.shape

(100, 3)

In [29]:
array1[:, 1] # column 2 

array([-3.06161700e-15, -1.56016723e+00, -2.96453965e+00, -4.07287976e+00,
       -4.77451121e+00, -4.99937064e+00, -4.72500409e+00, -3.97880920e+00,
       -2.83529932e+00, -1.40866278e+00,  1.58639667e-01,  1.71010072e+00,
        3.09079493e+00,  4.16284927e+00,  4.81921079e+00,  4.99433670e+00,
        4.67073930e+00,  3.88073232e+00,  2.70320409e+00,  1.25573994e+00,
       -3.17119598e-01, -1.85831228e+00, -3.21393805e+00, -4.24862715e+00,
       -4.85905784e+00, -4.98427388e+00, -4.61177147e+00, -3.77874787e+00,
       -2.56838696e+00, -1.10155266e+00,  4.75280217e-01,  2.00465268e+00,
        3.33384500e+00,  4.33012702e+00,  4.89401223e+00,  4.96919232e+00,
        4.54815998e+00,  3.67295854e+00,  2.43098368e+00,  9.46256222e-01,
       -6.32962268e-01, -2.14897456e+00, -3.45039506e+00, -4.40726682e+00,
       -4.92403877e+00, -4.94910721e+00, -4.47996887e+00, -3.56347086e+00,
       -2.29113261e+00, -7.90006980e-01,  7.90006980e-01,  2.29113261e+00,
        3.56347086e+00,  

In [30]:
array1[4, :] # row 5 

array([  1.37444086,  -4.77451121, -14.4386329 ])

In [33]:
np.amin(array1, axis=0) 

array([  0.02357813,  -4.99937064, -15.70796327])

In [34]:
np.amax(array1, axis=1)

array([ 4.28517983,  4.16158172,  3.59973217,  1.99456845,  1.37444086,
        0.39548055,  1.36597596,  0.85800362,  3.20752121,  3.78656065,
        3.15400343,  3.55363895,  3.09079493,  4.16284927,  4.81921079,
        4.9943367 ,  4.6707393 ,  3.88073232,  4.64142653,  2.17909942,
        3.66645822,  1.51373307,  2.63394856,  1.07991438,  1.64583491,
        1.18421233,  3.65952731,  1.55877621,  3.20550493,  2.53889331,
        1.27913496,  2.10578729,  3.333845  ,  4.33012702,  4.89401223,
        4.96919232,  4.54815998,  4.3665693 ,  2.68433168,  4.35335363,
        4.39114631,  2.40492377,  4.00775343,  0.27150782,  3.16533639,
        1.26971446,  1.15201351,  4.46373808,  4.96806287,  2.02211116,
        4.08494024,  2.34689108,  3.56347086,  4.47996887,  4.94910721,
        4.92403877,  4.40726682,  3.45039506,  2.93890655,  4.50959944,
        3.33199221,  4.6108272 ,  4.06443392,  4.28398998,  4.60132257,
        4.91865516,  5.23598776,  5.55332035,  5.87065294,  6.18

In [35]:
np.mean(array1, axis=0)

array([ 2.42021041e+00, -8.48470246e-17,  1.49213975e-15])

In [36]:
np.sum(array1, axis=1)

array([-11.42278344, -12.78921618, -14.43810556, -16.83427681,
       -17.83870325, -18.7251904 , -17.16299585, -16.60744071,
       -12.79708065, -10.47407208,  -9.22199426,  -6.95356509,
        -6.59301516,  -6.78429868,  -3.19398803,  -5.88296875,
        -1.85380659,  -3.17328291,  -2.65134601,  -6.24380468,
        -6.01197282,  -9.38855806,  -9.30663575, -11.57802644,
       -11.30520401, -11.57471004,  -8.40956005,  -9.35995496,
        -6.18553274,  -5.06797747,  -4.43357035,  -1.76021297,
        -0.30840591,   2.48842666,   0.32631402,   0.4301488 ,
         4.77434059,   4.07287046,   1.46599056,   1.96761765,
         0.74352443,  -2.44137782,  -1.82263607,  -6.19842084,
        -3.50403163,  -5.10738941,  -4.43861943,   0.10693574,
         2.20093138,   1.07343789,   5.03361351,   5.11402258,
         6.24617842,   6.33082879,   8.50830169,   9.90935431,
         9.06794995,   8.25249543,   7.78520813,   8.15722132,
         3.90968175,   5.82916832,   4.35813277,   3.56

In [37]:
np.sqrt(np.amax(array1, axis=1))

array([2.07006759, 2.03999552, 1.89729602, 1.41229191, 1.1723655 ,
       0.62887244, 1.16874974, 0.92628485, 1.79095539, 1.9459087 ,
       1.77595141, 1.8851098 , 1.75806568, 2.04030617, 2.1952701 ,
       2.23480127, 2.16118933, 1.96995744, 2.15439702, 1.4761773 ,
       1.91479979, 1.2303386 , 1.62294441, 1.03918929, 1.28290097,
       1.0882152 , 1.9129891 , 1.2485096 , 1.7903924 , 1.59339051,
       1.13098849, 1.45113311, 1.82588198, 2.08089573, 2.21224145,
       2.22916853, 2.13264155, 2.08963377, 1.63839302, 2.08646918,
       2.09550622, 1.55078166, 2.00193742, 0.52106413, 1.77913923,
       1.12681607, 1.07331892, 2.11275604, 2.22891518, 1.42200955,
       2.02112351, 1.53195662, 1.88771578, 2.1165937 , 2.2246589 ,
       2.21901752, 2.09934914, 1.8575239 , 1.71432393, 2.12358175,
       1.82537454, 2.14728368, 2.01604413, 2.06978018, 2.14506936,
       2.21780413, 2.28822808, 2.3565484 , 2.42294303, 2.48756619,
       2.55055251, 2.61202043, 2.67207472, 2.73080865, 2.78830

In [38]:
array2 = np.array([[[0], [2], [4]],[[1], [3], [5]]]) #array2 given

In [39]:
array2.shape

(2, 3, 1)

In [40]:
array2.reshape((2, 3))

array([[0, 2, 4],
       [1, 3, 5]])

## Part 2

In [42]:
import matplotlib.pyplot as plt

In [51]:
figure = plt.figure(figsize=(12, 8))

<Figure size 864x576 with 0 Axes>

In [52]:
plot1 = figure.subplots()
plot1.plot(array1[:, 1], array1[:, 0], 'm--')
plt.show()