**YOUR NAME HERE**

Spring 2020

CS 251B: Data Analysis and Visualization

Project 3: Linear Regression

In [1]:
import os
import random
import numpy as np
import matplotlib.pyplot as plt

import data
import linear_regression 

plt.style.use(['seaborn-colorblind', 'seaborn-darkgrid'])
plt.rcParams.update({'font.size': 20})

np.set_printoptions(suppress=True, precision=5)

# Automatically reload external modules
%load_ext autoreload
%autoreload 2

## Notes

- In your implementations, only the following "high level" `scipy`/`numpy` functions can be used:
    - `np.linalg.inv`
    - `scipy.linalg.lstsq` (in `LinearRegression::linear_regression_scipy` only).
    - `np.linalg.norm`

## Task 1: Run a linear regression

In this task, you will implement linear regression using the built-in SciPy least-squares solver, then analyze and plot the results on the Iris dataset. 

### 1a) Import Iris data

**TODO:**
- In the below cell, load in the Iris dataset into a `Data` object.
- Print out the object (only showing the first few data samples).
- Create an `LinearRegression` object called `lin_reg` based on the `Data` object that you just created.

In [2]:
iris_fp = 'data/iris.csv'
iris_data = data.Data(iris_fp)

print(iris_data)

lin_reg = linear_regression.LinearRegression(iris_data)

data/iris.csv (150x5)
Headers:
sepal_length sepal_width petal_length petal_width species 
Types:
numeric numeric numeric numeric numeric 
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


Your code should print something that looks like this:

    -------------------------------
    data/iris.csv (150x5)
    Headers:
    sepal_length	sepal_width	petal_length	petal_width	species
    Types:
    numeric	numeric	numeric	numeric	numeric
    -------------------------------
    Showing first 5/150 rows.
    5.1	3.5	1.4	0.2	0.0
    4.9	3.0	1.4	0.2	0.0
    4.7	3.2	1.3	0.2	0.0
    4.6	3.1	1.5	0.2	0.0
    5.0	3.6	1.4	0.2	0.0

### 1b) Use SciPy's built-in least squares solver to perform linear regression

Implement the following methods that are necessary to perform and analyze a linear regression.

- `linear_regression_scipy`: Uses the built-in least squares solver in the `scipy` module to perform linear regression. **Run test code below.**
- `predict`: Use fitted linear regression model coefficients to make predictions based on the data. **Run test code below.**
- `r_squared`: Quality of fit metric for linear regression.
- `compute_residuals`: Compute the difference between the regression model predictions and the actual dependent variable values (residuals).
- `linear_regression`: This is the method that brings together everything you've implemented so far and is the "front-facing" method that you want to call if you want to do a linear regression. The methods you have implemented thus far are "helper methods". **Run test code below.**

**$R^2$ Equation:** $$1 - \frac{E}{S}$$ where $$E = \sum_i \left (y_i - \hat{y}_i \right )^2$$ and $$S =  \sum_i \left (y_i - \bar{y} \right )^2$$ where $y_i$ are the dependent variable values, $\bar{y}_i$ is the mean of the dependent variable values, $\hat{y}_i$ is the y values *predicted* by the regression. 

#### Test `linear_regression_scipy`

In [17]:
np.random.seed(0)
# test data: 10 data samples, 4 dimensional.
test_A = np.random.normal(size=(10, 4))
test_y = np.random.normal(size=(10, 1))
test_c = lin_reg.linear_regression_scipy(test_A, test_y)
print(f'Your regression fit coefficients are\n{np.squeeze(test_c)} and should be\n[ 0.10874  0.58024  0.05166 -0.34    -0.54393]')
print(f'Your regression fit coefficient column vector shape is\n{test_c.shape} and should be\n(5, 1)')

Your regression fit coefficients are
[ 0.10874  0.58024  0.05166 -0.34    -0.54393] and should be
[ 0.10874  0.58024  0.05166 -0.34    -0.54393]
Your regression fit coefficient column vector shape is
(5, 1) and should be
(5, 1)


#### Test `predict`

In [18]:
np.random.seed(0)
# test data: 3 data samples, 4 dimensional.
test_slope = np.random.normal(size=(5, 1))
test_X = np.random.normal(size=(3, 5))
y_pred = lin_reg.predict(test_slope, np.pi, test_X)
print(f'Your model y predictions are\n{np.squeeze(y_pred)} and should be\n[2.18518 5.82409 3.23376]')
print(f'Your model y predictions shape is\n{y_pred.shape} and should be\n(3, 1)')

Your model y predictions are
[2.18518 5.82409 3.23376] and should be
[2.18518 5.82409 3.23376]
Your model y predictions shape is
(3, 1) and should be
(3, 1)


#### Test `linear_regression` method

In [20]:
lin_reg.linear_regression(['sepal_length'], 'petal_width', method='scipy')

# test shapes of instance variables
print(f'Shape of your A data array is\n{lin_reg.A.shape} and should be\n(150, 1)')
print(f'Shape of your y dep var vector is\n{lin_reg.y.shape} and should be\n(150, 1)\n')
print(f"Your independent variables are {lin_reg.ind_vars} and should be ['sepal_length']")
print(f'Your dependent variables are {lin_reg.dep_var} and should be petal_width\n')
print(f'Shape of your slope fits are {lin_reg.slope.shape} and should be (1, 1)')
print(f'Length of your intercept is {lin_reg.intercept.size} and should be 1')
print(f'Length of your R^2 is {lin_reg.R2.size} and should be 1\n')

# Test specific values
print(f'Your slope is {lin_reg.slope} and should be [[0.75292]]')
print(f'Your intercept is {lin_reg.intercept:.2f} and should be -3.20')
print(f'Your R^2 is {lin_reg.R2:.2f} and should be 0.67')
print(f'Your 1st few residuals are\n{lin_reg.residuals[:5].T} and should be\n[[-0.43966 -0.28908 -0.1385  -0.06321 -0.36437]]')

Shape of your A data array is
(150, 1) and should be
(150, 1)
Shape of your y dep var vector is
(150, 1) and should be
(150, 1)

Your independent variables are ['sepal_length'] and should be ['sepal_length']
Your dependent variables are petal_width and should be petal_width

Shape of your slope fits are (1, 1) and should be (1, 1)
Length of your intercept is 1 and should be 1
Length of your R^2 is 1 and should be 1

Your slope is [[0.75292]] and should be [[0.75292]]
Your intercept is -3.20 and should be -3.20
Your R^2 is 0.67 and should be 0.67
Your 1st few residuals are
[28.65225] and should be
[[-0.43966 -0.28908 -0.1385  -0.06321 -0.36437]]


## Task 2: Visualize linear regression

### 2a) Update `scatter` to support visualizing linear regression results

- Implement `scatter` in `linear_regression.py`: Call your `Analysis::scatter` method to make the scatter plot, then handle overlaying the regression line in `LinearRegression::scatter`. **Run test code below.**

#### Test  `scatter` with linear regression

Only run this when you're done implementing all the methods thru `linear_regression`. This should produce:
- A scatter plot with a linear regression line that looks like it makes sense.
- The title should have the linear regression method ("scipy") and the $R^2$ value.

In [ ]:
lin_reg.scatter('sepal_length', 'petal_width', 'scipy')
lin_reg.show()

### 2b) Update `pair_plot` to add regression lines to each scatter plot

- In the cell below, load in the `test52` data in a `Data` object.
    - Print the `Data object` (1st few lines only).
    - Create a `linear_regression` object based on the `Data` object.

#### Test `pair_plot()`

- Write `pair_plot()` in `linear_regression.py` that calls `Analysis::pair_plot` and extends it  to compute and plot the regression line for each scatter plot (all pairs of variables). **Run test code below.**

Executing the cell below should produce:
- A 5x5 grid of scatter plots.
- (*new*) regression lines in each scatter plot. The title of each subplot should have the $R^2$ value.
- Only 1st column has y axis labels.
- Only last column has x axis labels.

In [ ]:
lin_reg.pair_plot(test52_data.get_headers())

**Question 1:** Use the test pair plot to identify potential relationships among variables. Which variables appear to be most strongly related? Which variables appear least likely to be related?

**Answer 1:**

**Question 2:** What are the pros/cons of using pair plots to visualize multivariate data vs. a 3D scatter plot.

**Answer 2:**

### 2c) Making `pair_plot` more useful

- Update your `pair_plot` code to place a histogram along the main diagonal of the `pair_plot` grid (rather than a scatter plot). The matplotlib axis clear function should be useful.


Executing the cell below should produce:
- A 5x5 grid of scatter plots (histograms along main diagonal).
- Regression lines in each scatter plot. The title of each subplot should have the $R^2$ value.
- Only 1st column has y axis labels.
- Only last column has x axis labels.

In [ ]:
lin_reg.pair_plot(test52_data.get_headers())

**Question 3:** Which is more useful along diagonal, the histogram or scatterplot?

**Answer 3:**

## Task 3 Implement your own linear regression solver

In Tasks 1-2, you have used the SciPy least square solver to perform linear regression. In this task, you will solve the least squares problem directly using matrix math and compare the performance of the different methods on data.

- In the cell below, load in the Iris data again, make the `Data` object, create the `LinearRegression` object.

### 3a) Normal equations

This method involves solving the normal equations $$(A^TA)c = A^Ty$$

where:
- $A$ is the data matrix of independent variables selected for the regression shape=(`num_data_samps`, `num_ind_vars+1`) with an extra 1 column vector for the intercept
- $c$ is the vector of unknown regression coefficients associated with each independent variable (slopes + intercept) shape=(`num_ind_vars+1`,)
- $y$ is the dependent variable column vector shape=(`num_data_samps`,)

**TODO:**
- Implement the `linear_regression::linear_regression_normal` function. **Run test code below.**

In [ ]:
lin_reg_norm = linear_regression.LinearRegression(iris_data)
lin_reg_norm.linear_regression(['sepal_length'], 'petal_width', 'normal')
lin_reg_norm.scatter('sepal_length', 'petal_width', 'normal')
lin_reg_norm.show()