# Numpy tutorial 1

Oliver W. Layton

CS251: Data Analysis and Visualization

Spring 2020

In [4]:
import numpy as np

## Numpy ndarray basics

### Creation from Python lists

In [5]:
# Make a numpy array from a 2D python list
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
# print it
print(arr.dtype)
print(arr)

int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Data type of ndarray

In [7]:
# determine data type
print('Type of array is\n')

Type of array is



Type can be changed in a few ways. 

1. when creating array 鈥� (a) implicitly or (b) explicitly
2. by casting types.

In [8]:
# 1a implicitly (changing input literals)
arr = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
print(arr.dtype)

float64


In [9]:
# 1b explicitly
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
print(arr.dtype)

float64


In [10]:
# 2. NOTE: Casting is a METHOD of the array, not a FUNCTION
arr.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
# Can also be string. be careful in your CSV parser that your "numbers"
# aren't actually strings!
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=str)
print(arr.dtype)

<U1


### Convert back to Python list

In [12]:
# Convert back from ndarray to Python list (2 methods)
arr.tolist()

[['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']]

In [13]:
list(arr)

[array(['1', '2', '3'], dtype='<U1'),
 array(['4', '5', '6'], dtype='<U1'),
 array(['7', '8', '9'], dtype='<U1')]

### Other ways to create ndarrays quickly

#### 1. zeros

In [14]:
z = np.zeros([3, 90])
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

#### 2. ones

In [15]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# can easily make any constant array
9.5*one

array([9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5])

#### 3. Random values

In [17]:
# Uniform random values between 0 and 1
np.random.random([10, 10])

array([[9.53521243e-01, 1.40435829e-01, 7.83897792e-01, 8.47451523e-01,
        3.38736594e-01, 9.27101062e-01, 1.57838764e-01, 8.75955113e-01,
        6.87832587e-01, 4.15733084e-02],
       [3.68884073e-01, 8.88618112e-01, 4.17817573e-01, 2.77944875e-01,
        7.63200794e-01, 9.42856287e-01, 8.18691206e-01, 3.24429754e-01,
        7.01622632e-01, 5.20741541e-01],
       [8.14635322e-01, 7.18211113e-01, 6.21559057e-01, 3.78162960e-01,
        2.87316123e-01, 1.69647419e-01, 9.71881507e-01, 1.81306719e-01,
        1.78462843e-01, 6.28797381e-01],
       [3.90680508e-01, 4.61887222e-01, 6.16123377e-01, 6.37054880e-01,
        4.74025369e-01, 9.52895155e-01, 8.61623624e-01, 8.33442204e-01,
        4.92586273e-01, 3.88735467e-01],
       [5.05865906e-01, 9.82224075e-01, 7.93064145e-01, 1.54117034e-01,
        4.09440932e-02, 9.36132467e-01, 4.57130192e-01, 5.75359601e-01,
        7.77482418e-01, 1.50867858e-01],
       [1.56789104e-01, 3.15303714e-01, 7.35131690e-01, 9.48212051e-01,
   

#### 4. Equally spaced floats in an interval

In [18]:
np.linspace(-5, 5, 10)


array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [19]:
np.linspace(-5, 5, 2)

array([-5.,  5.])

#### 5. Equally spaced ints in an interval

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

#### 6. Identify matrix

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Check dimensions 鈥斅燻shape`

In [25]:
# check shape of 3D array
arr = np.ones([1, 2, 3])
arr.shape

(1, 2, 3)

In [26]:
# check number of dimensions (M)
arr = np.ones([1, 2, 3, 4, 5, 6])
arr.ndim

6

In [27]:
# Access 1st dim (#rows), 2nd dim (#cols) (Use f-string)
print(f"Number of rows/cols is {arr.shape[0]}/{arr.shape[1]}.")

Number of rows/cols is 1/2.


In [28]:
# Check number of elements total
arr = np.ones([1, 2, 3])
print(arr)
arr.size

[[[1. 1. 1.]
  [1. 1. 1.]]]


6

## Brief detour: Rapidly build python lists (list comprehension)

In [29]:
# Brief detour: In python you can replace the workflow of 
# list-building by creating an empty list and looping to append...
lst = [] 
for i in range(5):
    lst.append(i)
lst

[0, 1, 2, 3, 4]

In [31]:
# ...with Python list comprehensions
lst = [i for i in range(5)]
lst

[0, 1, 2, 3, 4]

In [32]:
# you can build lists using any function of i. How about i^2?
[i**2 for i in range(5)]

[0, 1, 4, 9, 16]

## ndarray indexing

Basic Accessing and modifying of ndarrays.

### Access and modify single elements

In [33]:
# To access elements in a multidimensional ndarray use ONE set of square brackets []
# Make a new random array
np.random.seed(0)  # ensures random numbers come up the same each time. Useful for debugging.
mat = np.random.random([5, 4])
mat

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [34]:
# Get the 1st element
mat[0, 0]

0.5488135039273248

In [36]:
# Modifying single values is similar
mat[0, 0] = 9
print('mat is now:\n', mat)

mat is now:
 [[9.         0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]]


### Slicing: real power of numpy

Use **colon** notation for all values in a dimension

Access and modify different ranges of data along different dimensions 

Make a 3x5 random array. Access 2nd column

In [37]:
np.random.seed(0)
arr = np.random.random([3, 5])
arr

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [38]:
arr[:, 1]

array([0.71518937, 0.43758721, 0.52889492])

Access 1st row

In [39]:
arr[0, :]

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

Access last 2 columns

In [41]:
arr[:, -2:]

array([[0.54488318, 0.4236548 ],
       [0.96366276, 0.38344152],
       [0.92559664, 0.07103606]])

Access columns at indices 1-2 and in 1st row. Careful about off-by-one.

- Low range (before :) CONTAINS that index
- High range (after :) DOES NOT contain that index (i-1)

In [42]:
arr[0, 1:3]

array([0.71518937, 0.60276338])

Use slicing to assign values efficiently in batch without loops

In [43]:
# Assign 1st row to -1s
arr[0] = -1
arr

array([[-1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152],
       [ 0.79172504,  0.52889492,  0.56804456,  0.92559664,  0.07103606]])

In [46]:
# Assign 1st row to increasing ints
arr[0] = np.arange(len(arr[0]))
arr

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [47]:
# Multiply the 3rd row by 5 times itself and update the row
arr[2] = 5 * arr[2]
arr

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [3.95862519, 2.6444746 , 2.84022281, 4.62798319, 0.35518029]])

### What if we want to access a set of rows or columns that are not adjacent?

Can't use colon notation. Instead use `np._ix`

In [48]:
arr

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [3.95862519, 2.6444746 , 2.84022281, 4.62798319, 0.35518029]])

Example: Say we want column indices 0, 2, 4 and all rows.

**Syntax for `np._ix`:**
- `np._ix` goes inside the square brackets: `arr[np._ix(blah)]`
- Give it `M` arguments (e.g. 2 for a 2D matrix).
- Each argument is a Python list (or ndarray) of indices to take along that dimension.

In [49]:
arr[np.ix_(np.arange(len(arr)), [0, 2, 4])]

array([[0.        , 2.        , 4.        ],
       [0.64589411, 0.891773  , 0.38344152],
       [3.95862519, 2.84022281, 0.35518029]])

## Memory

- Numpy tries to be efficient with arrays so assignment does a shallow copy. To do a deep copy, you need to use `.copy()` method

In [51]:
a = np.linspace(-1, 1, 5)
a

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [52]:
b = a 
b[0] = 9
print(a)
print(b)

[ 9.  -0.5  0.   0.5  1. ]
[ 9.  -0.5  0.   0.5  1. ]


In [53]:
# fixed with .copy()
a = np.linspace(-1, 1, 5)
b = a.copy()
b[0] = 9
print(a)
print(b)

[-1.  -0.5  0.   0.5  1. ]
[ 9.  -0.5  0.   0.5  1. ]


## Apply functions over dimensions (`axes`)

- Axes are the numpy term for different ndarray dimensions. 
- Example: axis 0 are the rows, axis 1 are the columns, etc.
- We can apply functions over one or more axis super efficiently in one line of code! This is called **Vectorization**聽鈥斅燤UCH MUCH faster than loops (stay tuned).

In [54]:
one = np.ones([5, 3])
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Sum along rows -> "collapse" across rows to get sum within each column 鈥斅�5 numbers

In [55]:
np.sum(one, axis=0)

array([5., 5., 5.])

Sum along columns -> "collapse" across columns to get sum within each row 鈥斅�3 numbers

In [56]:
np.sum(one, axis=1)

array([3., 3., 3., 3., 3.])

**Careful:** Applying a function without specifying the axis may compute across the ENTIRE ndarray.

In [57]:
np.sum(one)

15.0

**Mnemonic trick:** Applying a function along an axis eliminates that dimension from the shape. Left with remaining dimensions.

In [59]:
print(one.shape)
the_mean = np.mean(one, axis=0)
print(f'Mean across axis 0: {the_mean.shape}')

print(one.shape)
the_mean = np.mean(one, axis=1)
print(f'Mean across axis 1: {the_mean.shape}')

(5, 3)
Mean across axis 0: (3,)
(5, 3)
Mean across axis 1: (5,)


## Broadcasting

**This is the most useful numpy feature thus far! This will become your bread-and-butter!**

### Simple example: Scalars

As we saw, we can create an array of any size with any constant value WITHOUT ANY LOOPS. This is the simplest example of numpy **broadcasting** the scalar across the ndarray.

In [60]:
# Example with basic arithmetic
arr = 3*np.ones([5, 5]) + 10
arr

array([[13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.]])

### Example: Subtract the minimum value of each column for the original 2D array

In [75]:
np.random.seed(0)
rand_inds = np.random.randint(low=1, high=5, size=(5, 6))
rand_inds

array([[1, 4, 2, 1, 4, 4],
       [4, 4, 2, 4, 2, 3],
       [1, 4, 3, 1, 1, 1],
       [3, 2, 3, 4, 4, 3],
       [1, 2, 2, 2, 2, 1]])

In [76]:
np.min(rand_inds, axis=0)

array([1, 2, 2, 1, 1, 1])

In [77]:
# Take the min across each column and subtract it from rand_inds. Print shape of result
result = rand_inds - np.min(rand_inds, axis=0)
print(result)
print(result.shape)

[[0 2 0 0 3 3]
 [3 2 0 3 1 2]
 [0 2 1 0 0 0]
 [2 0 1 3 3 2]
 [0 0 0 1 1 0]]
(5, 6)


#### What's going on??

Let's look at the shapes:

In [78]:
print(rand_inds.shape)
print(np.min(rand_inds, axis=0).shape)

(5, 6)
(6,)


Numpy is **broadcasting** the vector to operate on the 2d ndarray (**draw this out on board**):

- Numpy looks for axis shape compatibility among the different arrays.
- Numpy sees the column dimension (5, **6**) matches the min vector (**6,**)
- Numpy adds a **singleton dimension** (a "fake" leading dimension for rows). Now the min vector is treated with shape: **(1, 6)**.
- Numpy dynamically "grows" the singleton dimension to the needed shape (5). So now the min vector is treated like a (5, 6) array.
- Numpy element-wise subtracts the two arrays: (5, 6) array can be subtracted by a (5, 6) array.
- Numpy returns the result, which is a (5, 6) array!

Process is **very memory efficient**: No new memory gets allocated during broadcasting.

#### Broadcasting only adds singleton dimensions LEFTWARD to the ndarray with smaller number of dimensions.

What if we did the same thing as above, but now wanted to **subtract the minimum value in each row**?

In [79]:
print(f'rand_inds shape: {rand_inds.shape}')
print(f'min shape: {np.min(rand_inds, axis=1).shape}')

rand_inds shape: (5, 6)
min shape: (5,)


In [80]:
# not working below
# rand_inds - np.min(rand_inds, axis=1) 

**Problem:** adding singleton dimensions to the LEFT could never make the shapes compatible!! For example, numpy tries: 

    rand_inds shape: (5, 6)
    min shape: (1, 5)

but that won't work! Crash...

#### Adding singleton dimensions by ourselves

We can help numpy out and add a "new axis" ourselves to make the shapes compatible with `np.newaxis`!

In [81]:
np.shape(np.min(rand_inds, axis=1)[:, np.newaxis])

(5, 1)

In [82]:
rand_inds - np.min(rand_inds, axis=1)[:, np.newaxis]

array([[0, 3, 1, 0, 3, 3],
       [2, 2, 0, 2, 0, 1],
       [0, 3, 2, 0, 0, 0],
       [1, 0, 1, 2, 2, 1],
       [0, 1, 1, 1, 1, 0]])

Can also make this more readable by defining a temp variable...

#### Squeeze if you need to get rid of all singleton dimensions

"Undo" a new axis / singleton dimension

In [83]:
ex = np.zeros([1, 2, 1, 3, 1, 4, 5, 1])
ex.shape

(1, 2, 1, 3, 1, 4, 5, 1)

In [84]:
np.squeeze(ex).shape

(2, 3, 4, 5)

#### Not automatically squeezing computations

As we saw above, functions like `min` over an axis eliminate that axis from the result: 

In [88]:
print(f'Min over axis 0 shape: {np.min(rand_inds, axis=0).shape}')
print(f'Min over axis 1 shape: {np.min(rand_inds, axis=1).shape}')

Min over axis 0 shape: (6,)
Min over axis 1 shape: (5,)


If we want `min` (and some other functions) to keep the singleton dimension, we can use the optional argument `keepdims=True`:

In [89]:
print(f'Min over axis 0 shape: {np.min(rand_inds, axis=0, keepdims=True).shape}')
print(f'Min over axis 1 shape: {np.min(rand_inds, axis=1, keepdims=True).shape}')

Min over axis 0 shape: (1, 6)
Min over axis 1 shape: (5, 1)


This can **help with broadcasting compatibility when performing an operation on an axis then modifying the original ndarray.** Then we don't need to manually add a new axis.

Example with subtracting the mean:

In [ ]:
# Subtract off mean along either axis
rand_inds_centered = rand_inds.copy()

## Vectorization speed vs loops

Time computation of adding 1 to a ndarray with loop vs vectorized.

In [92]:
import time
def timeit(fun):
    '''Just a function to time the runtime of another function'''
    def timer():
        start = time.time()
        fun()
        end = time.time()
        print(f'Took {end - start:.3} secs to run.')
    return timer


@timeit
def addOneLoop():
    '''Use for loop to add 1 to row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    for i in range(len(longRow)):
        longRow[i] = longRow[i] + 1


@timeit
def addOneVectorized():
    '''Vectorized version of adding 1 to row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    longRow = longRow + 1

In [93]:
# Dynamic typing in python makes for loops with lots of small
# operations slow
print('addOneLoop:')
addOneLoop()

# Vectorization allows Numpy to stop searching at runtime
# and use efficient pre-compiled functions to batch-process
# the computation over the matrix
print('addOneVectorized:')
addOneVectorized()

addOneLoop:
Took 0.688 secs to run.
addOneVectorized:
Took 0.157 secs to run.


## Switching around the axes of an ndarray and matrix multiplication in numpy

We can't matrix multiply the following ndarrays due to shape issues:

In [ ]:
a = 3*np.ones([3, 4])
b = 2*np.ones([3, 4])

Need to pair up as

    (3, 4) x (4, 3)

OR

    (4, 3) x (3, 4)
    
Use the transpose to help out!

Note: Transposing a ndarray vector isn't meaningful if you don't have a singleton dimension

### Matrix vs. element-wise multiplication

- Star (*) operator means element-wise multiplication
- Like other basic math operators, can use broadcasting (e.g. can multiply a (3,) and a (5, 3) array)