# Numpy tutorial 1

Oliver W. Layton

CS251: Data Analysis and Visualization

Spring 2020

In [1]:
import numpy as np

## Numpy ndarray basics

### Creation from Python lists

In [2]:
# Make a numpy array from a 2D python list
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
# print it
print(arr.dtype)
print(arr)

int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Data type of ndarray

In [ ]:
# determine data type
print('Type of array is\n')

Type can be changed in a few ways. 

1. when creating array 鈥� (a) implicitly or (b) explicitly
2. by casting types.

In [5]:
# 1a implicitly (changing input literals)
arr = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
print(arr.dtype)

float64


In [8]:
# 1b explicitly
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
print(arr.dtype)

float64


In [18]:
# 2. NOTE: Casting is a METHOD of the array, not a FUNCTION
arr.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
# Can also be string. be careful in your CSV parser that your "numbers"
# aren't actually strings!
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=str)
print(arr.dtype)

### Convert back to Python list

In [21]:
# Convert back from ndarray to Python list (2 methods)
arr.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [22]:
list(arr)

[array([1., 2., 3.]), array([4., 5., 6.]), array([7., 8., 9.])]

### Other ways to create ndarrays quickly

#### 1. zeros

In [9]:
z = np.zeros([3, 90])
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

#### 2. ones

In [10]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# can easily make any constant array
9.5*one

array([9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5])

#### 3. Random values

In [12]:
# Uniform random values between 0 and 1
np.random.random([10, 10])

array([[0.6247684 , 0.39989018, 0.13147557, 0.26956735, 0.19979544,
        0.0441856 , 0.50592495, 0.18885845, 0.77452284, 0.44026789],
       [0.19360278, 0.55378245, 0.94701623, 0.51534194, 0.00741745,
        0.347113  , 0.42651615, 0.82048965, 0.8403929 , 0.61023874],
       [0.66338228, 0.4684449 , 0.31085544, 0.29830284, 0.81124928,
        0.90411392, 0.78797658, 0.39678741, 0.3128222 , 0.34282364],
       [0.01738182, 0.80817778, 0.48552477, 0.10272942, 0.67099348,
        0.39125974, 0.33607485, 0.58276901, 0.83545865, 0.14956682],
       [0.8699355 , 0.52854634, 0.42250455, 0.90251969, 0.27068242,
        0.73123522, 0.79797924, 0.54567258, 0.36509464, 0.92776205],
       [0.03455543, 0.669774  , 0.7321557 , 0.22002032, 0.50338923,
        0.29784024, 0.94220018, 0.67536223, 0.95356092, 0.04922888],
       [0.39291647, 0.22427393, 0.82635374, 0.41955206, 0.76670749,
        0.2007698 , 0.75229564, 0.3394071 , 0.1007171 , 0.79224013],
       [0.8918108 , 0.48249601, 0.4298936

#### 4. Equally spaced floats in an interval

In [16]:
np.linspace(-5, 5, 10)


array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [15]:
np.linspace(-5, 5, 2)

array([-5.,  5.])

#### 5. Equally spaced ints in an interval

#### 6. Identify matrix

### Check dimensions 鈥斅燻shape`

In [ ]:
# check shape of 3D array


In [ ]:
# check number of dimensions (M)


In [ ]:
# Access 1st dim (#rows), 2nd dim (#cols) (Use f-string)


In [ ]:
# Check number of elements total


## Brief detour: Rapidly build python lists (list comprehension)

In [ ]:
# Brief detour: In python you can replace the workflow of 
# list-building by creating an empty list and looping to append...


In [ ]:
# ...with Python list comprehensions


In [ ]:
# you can build lists using any function of i. How about i^2?


## ndarray indexing

Basic Accessing and modifying of ndarrays.

### Access and modify single elements

In [ ]:
# To access elements in a multidimensional ndarray use ONE set of square brackets []
# Make a new random array
np.random.seed(0)  # ensures random numbers come up the same each time. Useful for debugging.


In [ ]:
# Get the 1st element


In [ ]:
# Modifying single values is similar

print('arr is now:\n', arr)

### Slicing: real power of numpy

Use **colon** notation for all values in a dimension

Access and modify different ranges of data along different dimensions 

Make a 3x5 random array. Access 2nd column

In [ ]:
np.random.seed(0)


Access 1st row

Access last 2 columns

Access columns at indices 1-2 and in 1st row. Careful about off-by-one.

- Low range (before :) CONTAINS that index
- High range (after :) DOES NOT contain that index (i-1)

Use slicing to assign values efficiently in batch without loops

In [ ]:
# Assign 1st row to -1s


In [ ]:
# Assign 1st row to increasing ints


In [ ]:
# Multiply the 3rd row by 5 times itself and update the row


### What if we want to access a set of rows or columns that are not adjacent?

Can't use colon notation. Instead use `np._ix`

In [ ]:
arr

Example: Say we want column indices 0, 2, 4 and all rows.

**Syntax for `np._ix`:**
- `np._ix` goes inside the square brackets: `arr[np._ix(blah)]`
- Give it `M` arguments (e.g. 2 for a 2D matrix).
- Each argument is a Python list (or ndarray) of indices to take along that dimension.

## Memory

- Numpy tries to be efficient with arrays so assignment does a shallow copy. To do a deep copy, you need to use `.copy()` method

In [ ]:
a = np.linspace(-1, 1, 5)
a

In [ ]:
# fixed with .copy()

## Apply functions over dimensions (`axes`)

- Axes are the numpy term for different ndarray dimensions. 
- Example: axis 0 are the rows, axis 1 are the columns, etc.
- We can apply functions over one or more axis super efficiently in one line of code! This is called **Vectorization**聽鈥斅燤UCH MUCH faster than loops (stay tuned).

Sum along rows -> "collapse" across rows to get sum within each column 鈥斅�5 numbers

Sum along columns -> "collapse" across columns to get sum within each row 鈥斅�3 numbers

**Careful:** Applying a function without specifying the axis may compute across the ENTIRE ndarray.

In [ ]:
)

**Mnemonic trick:** Applying a function along an axis eliminates that dimension from the shape. Left with remaining dimensions.

In [ ]:
print(one.shape)

print(f'Mean across axis 0: {the_mean.shape}')

print(one.shape)

print(f'Mean across axis 1: {the_mean.shape}')

## Broadcasting

**This is the most useful numpy feature thus far! This will become your bread-and-butter!**

### Simple example: Scalars

As we saw, we can create an array of any size with any constant value WITHOUT ANY LOOPS. This is the simplest example of numpy **broadcasting** the scalar across the ndarray.

In [ ]:
# Example with basic arithmetic


### Example: Subtract the minimum value of each column for the original 2D array

In [ ]:
np.random.seed(0)
rand_inds = np.random.randint(low=0, high=5, size=(5, 6))
rand_inds

In [ ]:
# Take the min across each column and subtract it from rand_inds. Print shape of result

print(result.shape)

#### What's going on??

Let's look at the shapes:

Numpy is **broadcasting** the vector to operate on the 2d ndarray (**draw this out on board**):

- Numpy looks for axis shape compatibility among the different arrays.
- Numpy sees the column dimension (5, **6**) matches the min vector (**6,**)
- Numpy adds a **singleton dimension** (a "fake" leading dimension for rows). Now the min vector is treated with shape: **(1, 6)**.
- Numpy dynamically "grows" the singleton dimension to the needed shape (5). So now the min vector is treated like a (5, 6) array.
- Numpy element-wise subtracts the two arrays: (5, 6) array can be subtracted by a (5, 6) array.
- Numpy returns the result, which is a (5, 6) array!

Process is **very memory efficient**: No new memory gets allocated during broadcasting.

#### Broadcasting only adds singleton dimensions LEFTWARD to the ndarray with smaller number of dimensions.

What if we did the same thing as above, but now wanted to **subtract the minimum value in each row**?

In [ ]:
print(f'rand_inds shape: {rand_inds.shape}')
print(f'min shape: {np.min(rand_inds, axis=1).shape}')

**Problem:** adding singleton dimensions to the LEFT could never make the shapes compatible!! For example, numpy tries: 

    rand_inds shape: (5, 6)
    min shape: (1, 5)

but that won't work! Crash...

#### Adding singleton dimensions by ourselves

We can help numpy out and add a "new axis" ourselves to make the shapes compatible with `np.newaxis`!

Can also make this more readable by defining a temp variable...

#### Squeeze if you need to get rid of all singleton dimensions

"Undo" a new axis / singleton dimension

In [ ]:
ex = np.zeros([1, 2, 1, 3, 1, 4, 5, 1])
ex.shape

#### Not automatically squeezing computations

As we saw above, functions like `min` over an axis eliminate that axis from the result: 

In [ ]:
print(f'Min over axis 0 shape: {.shape}')
print(f'Min over axis 1 shape: {.shape}')

If we want `min` (and some other functions) to keep the singleton dimension, we can use the optional argument `keepdims=True`:

In [ ]:
print(f'Min over axis 0 shape: {.shape}')
print(f'Min over axis 1 shape: {.shape}')

This can **help with broadcasting compatibility when performing an operation on an axis then modifying the original ndarray.** Then we don't need to manually add a new axis.

Example with subtracting the mean:

In [ ]:
# Subtract off mean along either axis
rand_inds_centered = rand_inds.copy()

## Vectorization speed vs loops

Time computation of adding 1 to a ndarray with loop vs vectorized.

In [ ]:
def timeit(fun):
    '''Just a function to time the runtime of another function'''
    def timer():
        start = time.time()
        fun()
        end = time.time()
        print(f'Took {end - start:.3} secs to run.')
    return timer


@timeit
def addOneLoop():
    '''Use for loop to add 1 to row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    for i in range(len(longRow)):
        longRow[i] = longRow[i] + 1


@timeit
def addOneVectorized():
    '''Vectorized version of adding 1 to row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    longRow = longRow + 1

In [ ]:
# Dynamic typing in python makes for loops with lots of small
# operations slow
print('addOneLoop:')
addOneLoop()

# Vectorization allows Numpy to stop searching at runtime
# and use efficient pre-compiled functions to batch-process
# the computation over the matrix
print('addOneVectorized:')
addOneVectorized()

## Switching around the axes of an ndarray and matrix multiplication in numpy

We can't matrix multiply the following ndarrays due to shape issues:

In [ ]:
a = 3*np.ones([3, 4])
b = 2*np.ones([3, 4])

Need to pair up as

    (3, 4) x (4, 3)

OR

    (4, 3) x (3, 4)
    
Use the transpose to help out!

Note: Transposing a ndarray vector isn't meaningful if you don't have a singleton dimension

### Matrix vs. element-wise multiplication

- Star (*) operator means element-wise multiplication
- Like other basic math operators, can use broadcasting (e.g. can multiply a (3,) and a (5, 3) array)